version: '2'
services:
  users-service:
    build: ./users-service
    container_name: users_service
    ports:
     - "8080:8080"
    links:
      - db:db
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
  db:
    build: ./test-database
