version: '2'
services:
  coffee_shop:
    image: majdangabriel/coffee_shop
    build: ./coffee_shop
    container_name: coffee_shop
    ports:
     - "80:80"

  coffee_menu:
    image: majdangabriel/coffee_menu
    build: ./coffee_menu
    container_name: coffee_menu
    ports:
     - "8080:8080"
    links:
     - coffee_menu_db:coffee_menu_db
    depends_on:
     - coffee_menu_db
    environment:
     - DATABASE_HOST=coffee_menu_db
  coffee_menu_db:
    image: majdangabriel/coffee_menu_db
    build: ./coffee_menu_db

  coffee_order:
    image: majdangabriel/coffee_order
    build: ./coffee_order
    container_name: coffee_order
    ports:
     - "8081:8081"
    links:
     - coffee_order_db:coffee_order_db
    depends_on:
     - coffee_order_db
    environment:
     - DATABASE_HOST=coffee_order_db
  coffee_order_db:
    image: majdangabriel/coffee_order_db
    build: ./coffee_order_db
