version: '2'
services:
  coffee-shop:
    build: ./coffee-shop
    container_name: coffee-shop
    ports:
     - "8080:8080"
    links:
     - coffee_menu_db:coffee_menu_db
    depends_on:
     - coffee_menu_db
    environment:
     - DATABASE_HOST=coffee_menu_db
  coffee_menu_db:
    build: ./coffee_menu_db
